### ISSUE TITLE
I have some problems while running code

### ISSUE THREAD

**Issue by JuNeF1** [MattiaLitrico/Guiding-Pseudo-labels-with-Uncertainty-Estimation-for-Test-Time-Adaptation#9]
The terminal showed that  File "/home/songchenhao/.local/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 143, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0

I have arrange the dataset at  <root file>/VISDA-C 
ANY help? I will be appreciated if you see this issue, anyway THANKS

**Comment by MattiaLitrico** [comment]
This means that the path of the dataset is not correct. Check if in visdac.py the data are loaded from the correct directory.

**Comment by maninblack6** [comment]
Hello,I got the same problem,did you solve it?Please tell me,thanks

**Comment by JuNeF1** [comment]
> Hello,I got the same problem,did you solve it?Please tell me,thanks

Yep，locate the terminal message /home/songchenhao/.local/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 143.I remember there were two dataload functions.You just need to change the first function shuffle vaule to FALSE .It should be like 
self.train_dataloader = DataLoader(train_dataset, batch_size=TrainOption.train_batch_size, shuffle=FALSE,
                                           num_workers=TrainOption.data_load_worker_num)

**Comment by a1324yn** [comment]
> > Hello,I got the same problem,did you solve it?Please tell me,thanks
> 
> Yep，locate the terminal message /home/songchenhao/.local/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 143.I remember there were two dataload functions.You just need to change the first function shuffle vaule to FALSE .It should be like self.train_dataloader = DataLoader(train_dataset, batch_size=TrainOption.train_batch_size, shuffle=FALSE, num_workers=TrainOption.data_load_worker_num)

The solution you provided seems to be incorrect. This might be due to an error in the script you provided. For instance, in ‘train_VISDA-C_source.sh’, the command ‘–dataset visdac/source’ might point to an incorrect path. It would be better to rename the dataset or modify the code to ‘–dataset visdac/train’.
